import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import MuiProvider from "./MuiProvider";
import LogoutButton from "@/components/buttons/SingnOut";
import { Avatar, Box, Tooltip, Typography } from "@mui/material";
import NextAuth, { getServerSession } from "next-auth/next";
import authOptions from "@/authOptions";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AppRouterCacheProvider>
          <MuiProvider>
            {session && (
              <Box sx={{ position: "absolute", right: "0px" }}>
                <Tooltip title={session?.user?.name || ""}>
                  <Avatar sx={{ float: "left" }} alt={session?.user?.name || ""} src={session?.user?.image || ""} />
                </Tooltip>

                <LogoutButton sx={{ float: "right", marginTop: "0.3rem" }} />
              </Box>
            )}

            {children}
          </MuiProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
